const String mainUrl = 'https://gofed.in/';
const String apiUrl = mainUrl + 'Partner/';

const String userUrl = mainUrl + 'Partner/';
const String datalistUrl = mainUrl + 'Datalist/';
const String mobileVerifyUrl = userUrl + 'mobileVerify';
const String updateOnlineStatusUrl = userUrl + 'updateOnlineStatus';
const String updateTokenUrl = userUrl + 'updateToken';
const String updateProfileUrl = userUrl + 'updateProfile';
const String loginUrl = userUrl + 'login';
const String registerUrl = userUrl + 'register';
const String registerStep2Url = userUrl + 'register_step2';
const String registerStatusUrl = userUrl + 'register_status';
const String profileUrl = userUrl + 'userDetails';
const String profileVehicleUrl = userUrl + 'profile';
const String purposeListUrl = userUrl + 'regPurposeList';
const String stateListUrl = datalistUrl + 'stateList';
const String cityListUrl = datalistUrl + 'cityList?state=';
const String uploadUrl = userUrl + 'kycUpload';
const String vehicleFitnessUploadUrl = userUrl + 'vehicleFitnessUpload';
const String kycStatusUrl = userUrl + 'kycStatus';
const String cityList = datalistUrl + 'cityList?state=10';
const String languagesUrl = datalistUrl + "languages";
const String setTrainingLanguageUrl = userUrl + "setPrefTrainingLang";
const String setPrefAppLangUrl = userUrl + "setPrefAppLang";
const String trainingUrl = userUrl + "training";
const String updateTrainingUrl = userUrl + "updateTraining";
const String notificationUrl = userUrl + "notification";
const String orderUrl = userUrl + "orders";
const String workingCitiesUrl = datalistUrl + 'working_cities';
const String rideListUrl = userUrl + 'rideList';
const String vehicleTypeListUrl = datalistUrl + 'vehicleTypeList';
const String insertTrackingUrl = userUrl + 'insertTracking';
const String earningUrl = userUrl + 'earning';
const String walletUrl = userUrl + 'wallet';
const String rideHistoryUrl = userUrl + 'rideHistory';
const String withdrawRequestUrl = userUrl + 'withdrawRequest';
const String addMoneyUrl = userUrl + 'addMoney';
const String acceptRideUrl = userUrl + 'acceptRide';
const String anyRideActiveUrl = userUrl + 'anyRideActive';
const String ridePickedUrl = userUrl + 'ridePicked';
const String rideCompletedUrl = userUrl + 'rideCompleted';
const String rideCancelUrl = userUrl + 'rideCancel';
const String rideDetailsUrl = userUrl + 'rideDetails';
const String reviewUrl = datalistUrl + 'review';

var onlineGlobalValue = 0;
